version: '3.9'

services:
  app_alta:
    image: ganes556/alta-api-example:alpine
    container_name: alta_api
    env_file:
      - ./.env
    build:
      context: .
    ports:
      - '8000:8000'
    depends_on:
      db_alta:
        condition: service_healthy
    volumes:
      - alta_api_storage:/alta_api_storage

  db_alta:
    image: mysql
    container_name: db_mysql
    environment:
      MYSQL_DATABASE: alta_api
      MYSQL_ROOT_PASSWORD: altapass
    ports:
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-p$$MYSQL_ROOT_PASSWORD',
        ]
      timeout: 20s
      retries: 10

    volumes:
      - alta_api_storage:/var/lib/mysql

volumes:
  alta_api_storage:
