# fly.toml file generated for alta-api on 2023-04-16T08:11:05+08:00

app = "alta-api"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "sin"
processes = []

[[services]]
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[env]
  DB_USERNAME="root"
  DB_HOST="db-alta.internal"
  DB_NAME= "alta-api"