version: '3.0'

services:
  app:
    image: toko-electronic:alpine
    container_name: toko_electronic
    build:
      context: .
    env_file:
      - ./.env
    ports:
      - '8000:8000'
    networks:
      - db_mysql
      - docs
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql
    container_name: db_mysql
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-p $$MYSQL_ROOT_PASSWORD',
        ]
      timeout: 20s
      retries: 10
    networks:
      - db_mysql
    volumes:
      - ./db/backup:/var/lib/mysql

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - '80:8080'
    volumes:
      - ./docs/swagger:/usr/share/nginx/html/docs
    environment:
      URLS: "[{ url: 'docs/toko-electronic.yaml', name: 'API Toko Electronic'}]"
    networks:
      - docs

networks:
  db_mysql:
  docs:
