name: Testing

on:
  pull_request:
    branches: ['master']

jobs:
  test-section-28:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./28_CI-CD/pratikum

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Build
        run: |
          export GOPATH=$HOME/go
          go get .
          go build -v ./...

      - name: Test
        run: go test -v ./...
